#!/usr/bin/env python3
"""Generate MPTV overrides for :core strings that say "OwnTV".

Every user-visible string lives in :core (ahXN00/OwnTV_Core), and ~70 of them name the app
("Set up OwnTV", "Exit OwnTV?", ...) in every language. An app module's resource of the same name
and qualifier wins over the library's, so this writes one mptv_brand.xml per values folder with
those strings copied verbatim and "OwnTV" replaced by "MPTV".

Re-run after every core pin bump (the text drifts between versions):

    python3 tools/brand/mptv_strings.py <OwnTV_Core checkout at core-X.Y.Z> <app res dir>

  e.g. git clone --depth 1 --branch core-1.0.61 https://github.com/ahXN00/OwnTV_Core /tmp/core
       python3 tools/brand/mptv_strings.py /tmp/core app/src/main/res
       python3 tools/brand/mptv_strings.py /tmp/core mobile/app/src/main/res
"""
import pathlib
import re
import sys

ELEMENT = re.compile(r'<(string|plurals|string-array)\s+name="([^"]+)"[^>]*?(?:/>|>.*?</\1>)', re.S)
HEADER = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    "<!-- GENERATED by tools/brand/mptv_strings.py from :core's resources. Do not edit by hand;\n"
    '     re-run the script after a core pin bump. -->\n'
    '<resources xmlns:tools="http://schemas.android.com/tools"\n'
    '           xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">\n'
)


def app_defined_names(folder: pathlib.Path) -> set[str]:
    """Names the app already defines itself (e.g. app_name in strings.xml) — must not be duplicated."""
    names = set()
    for f in folder.glob("*.xml"):
        if f.name != "mptv_brand.xml":
            names.update(m.group(2) for m in ELEMENT.finditer(f.read_text(encoding="utf-8")))
    return names


def main(core_root: str, app_res: str) -> None:
    core_res = pathlib.Path(core_root) / "core" / "src" / "main" / "res"
    out_res = pathlib.Path(app_res)
    total = 0
    folders = sorted(core_res.glob("values*"))
    # name -> folder -> element, for every core string.
    core = {}
    for folder in folders:
        for f in sorted(folder.glob("*.xml")):
            for m in ELEMENT.finditer(f.read_text(encoding="utf-8")):
                core.setdefault(m.group(2), {})[folder.name] = m.group(0)
    # A string is overridden if it says OwnTV in ANY language, and then in EVERY language core has
    # it in, so the app module's own resources are complete (lint's MissingTranslation looks at them).
    names = {n for n, per in core.items() if any("OwnTV" in e for e in per.values())}
    for folder in folders:
        found = {n: core[n][folder.name].replace("OwnTV", "MPTV") for n in names if folder.name in core[n]}
        target_dir = out_res / folder.name
        target = target_dir / "mptv_brand.xml"
        if target_dir.is_dir():
            for name in app_defined_names(target_dir):
                found.pop(name, None)
        if not found:
            target.unlink(missing_ok=True)
            continue
        target_dir.mkdir(parents=True, exist_ok=True)
        body = "".join(f"    {found[k]}\n" for k in sorted(found))
        target.write_text(HEADER + body + "</resources>\n", encoding="utf-8")
        total += len(found)
    print(f"{out_res}: {total} strings overridden")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
